GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_path: datasets/WF_500_hip
fmap: 16
gap_t: 19
gap_x: 40
gap_y: 40
lr: 5.0e-05
n_epochs: 5
output_dir: ./results
overlap_factor: 0.6
patch_t: 300
patch_x: 100
patch_y: 100
pth_path: ./pth/WF_500_hip_202402271251
scale_factor: 1
select_img_num: 1000000
train_datasets_size: 6000
